// ### Create a new user
// POST http://localhost:3000/api/users
// Content-Type: application/json

// {
//     "useruid": "123",
//     "username": "testuser",
//     "userimage": "image.jpg",
//     "useremail": "test@example.com"
// }

// ### Get user details
// GET http://localhost:3000/api/users/123

// ### Update user details
// PUT http://localhost:3000/api/users/123
// Content-Type: application/json

// {
//     "username": "updateduser"
// }

// ### Delete user
// DELETE http://localhost:3000/api/users/123